### PR TITLE
Run publishLocal using nix sbt

### PR DESCRIPTION
**Pull request by dsebban**
Thanks for this repo @gvolpe , I am really enjoying nix, I think the README is missing this, I might be totally wrong as I am new to nix, let me know if it makes sense.
Without this I got this
Screen Shot 2020-12-21 at 11 14 20

### CODE REVIEW

**Comment by gvolpe** [comment]
@dsebban great to hear :)

You're not wrong, in order to access any software declared in the `shell.nix` you need to indeed run `nix-shell` or use something like `lorri` or `nix-direnv`.

In the beginning of the README, you can find these two sentences.

> It is very appealing for new members joining the team! On day one, all they need to do is to git-clone the project, install Nix, run nix-shell and all the project's dependencies will become available. Isn't that great?

> We can also use nix-direnv so that we don't even need to run nix-shell every time. Upon entering a working directory with a shell.nix, all the declared software will become automatically available. Feels like magic! Actually, this is what we promote using at work.

I think we can generalize instead of adding the instruction to a single example and add something below these sentences. Something like.

NOTE: in the following examples, we assume you are within a Nix shell to access software such as `sbt` and `java`.

WDYT?

**Comment by dsebban** [comment]
Sure, I just followed the tutorial and copy/paste stuff, you can't nix-build within a nix shell can you? , that's why I figured to add it there
Screen Shot 2020-12-21 at 12 33 14

**Comment by gvolpe** [comment]
Does not matter whether you run `nix-build` inside or outside the Nix shell, it should still work, that's odd. What OS are you on? You can try `echo $PATH` inside and outside the Nix shell and compare the results.

**Comment by gvolpe** [comment]
The `docker` daemon cannot be managed by Nix unless you're on NixOS, so `docker` needs to be installed globally.

**Comment by dsebban** [comment]
I am on Mac OS using tmux and zsh
Screen Shot 2020-12-21 at 12 43 11

**Comment by gvolpe** [comment]
Hmm can you try the same on a normal terminal (e.g. `iTerm2`)? That's probably `tmux` being funny but it could also be something `zsh` related..

**Comment by dsebban** [comment]
that's on vanilla terminal
Screen Shot 2020-12-21 at 12 54 06

**Comment by gvolpe** [comment]
What's your `nix` version? Try `nix build` instead.

**Comment by gvolpe** [comment]
Also please paste the outputs of `echo $PATH` both inside and outside Nix shell.

**Comment by dsebban** [comment]
Screen Shot 2020-12-21 at 13 04 38
Screen Shot 2020-12-21 at 13 07 47

**Comment by gvolpe** [comment]
It seems `/Users/danielsivan/.nix-profile/bin` is not present within your Nix shell. Could be something wrong with your Nix installation (I'd try re-installing Nix) or something else. I'm not a Mac user so can't help much, unfortunately.

**Comment by dsebban** [comment]
Thnks for the help !

**Pull request closed without merging**
